apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

secretGenerator:
- name: pgo-s3-creds
  files:
  - s3.conf

generatorOptions:
  disableNameSuffixHash: true

resources:
  - postgrescluster.yaml
  - configmap.yaml
  - job.yaml
