apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: safety-advisor-pg
spec:
  postgresVersion: 16

  instances:
    - name: primary
      replicas: 1
      dataVolumeClaimSpec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: microk8s-hostpath
        resources:
          requests:
            storage: 8Gi
      resources:
        requests:
          cpu: "250m"
          memory: "512Mi"
        limits:
          cpu: "500m"
          memory: "1Gi"
  users:
    - name: postgres
    - name: safety-advisor
      databases: ["safety_advisor"]
    - name: appsmith
      databases: ["safety_advisor"]

  patroni:
    dynamicConfiguration:
      postgresql:
        parameters:
          max_connections: "300"
