apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: safety-advisor

resources:
  - ../../base

patches:
  - path: postgrescluster-patch.yaml
    target:
      group: postgres-operator.crunchydata.com
      version: v1beta1
      kind: PostgresCluster
      name: safety-advisor-pg